version: '3.9'
services:
  dashboard:
    image: ghcr.io/gaia-qao/advent-dashboard:latest
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - telemetry
      - quantum
    networks:
      - gaia-net

  telemetry:
    image: ghcr.io/gaia-qao/advent-telemetry:latest
    restart: always
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=kafka:9092
      - INFLUXDB_URL=http://influxdb:8086
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - influxdb
    networks:
      - gaia-net

  quantum:
    image: ghcr.io/gaia-qao/advent-quantum:latest
    restart: always
    environment:
      - QUANTUM_BACKEND=${QUANTUM_BACKEND}
      - IBMQ_TOKEN=${IBMQ_TOKEN}
      - DWAVE_TOKEN=${DWAVE_TOKEN}
      - RIGETTI_TOKEN=${RIGETTI_TOKEN}
    networks:
      - gaia-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - gaia-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - gaia-net

  influxdb:
    image: influxdb:2.7
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=gaia
      - DOCKER_INFLUXDB_INIT_PASSWORD=gaia_prod_pass
      - DOCKER_INFLUXDB_INIT_ORG=gaia-qao
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=gaia-prod-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - gaia-net

networks:
  gaia-net:
    driver: bridge

volumes:
  influxdb-data:
